### ISSUE TITLE
KeyError: 'some_cookie_name'

### ISSUE THREAD

**Issue by andww** [fsmosca/sample-streamlit-authenticator#1]
Hi,
Thanks for the sample.....it served as a good base for me to learn Multipage Authenticator.

After login, if I click Logout immediately, I get this KeyError. However, if after login, and I click on other Pages then back to Account to logout, this error doesn't seem to happen. Seems like the cookie is not registered straight after login.

I am very new to python, sorry if I had made a newbie error somewhere. Any pointers are greatly appreciated.

![Screenshot 2024-03-16 at 05 30 23](https://github.com/fsmosca/sample-streamlit-authenticator/assets/19371060/cabccbaf-afd3-4285-9b49-2d00cc2b839c)

**Comment by fsmosca** [comment]
That is a bug from the streamlit-authenticator lib or from the cookie-manager that authenticator uses.

I fix this in [my branch from the fork](https://github.com/fsmosca/Streamlit-Authenticator/commit/9aabce66d189cd02d18bfec100648a97f590bac4).

If you want to try this branch do this.

1. In your requirements.txt use the following.

```
git+https://github.com/fsmosca/Streamlit-Authenticator.git@add-forgotpassword-key
```

Use that instead of streamlit-authenticator.

The other minor benefits is that in login and forgot password widget, you can specify a key for the form and you can clear the form after submission. See [examples](https://github.com/mkhorasani/Streamlit-Authenticator/issues/132#issuecomment-1991705455).

You should use the [official streamlit-authenticator](https://github.com/mkhorasani/Streamlit-Authenticator) once it is fixed there.

**Comment by fsmosca** [comment]
I just revised the requirements.txt file, I use the new streamlit version and the branch.

**Comment by andww** [comment]
Thanks for the very speedy reply. Will try the above. Trust it will be ok.
